### ISSUE TITLE
unable to clone  5G-EmPOWER eNB agent 

### ISSUE THREAD

**Issue by mimo123-code** [5g-empower/empower-enb-agent#2]
hello i am unable to clone the   5G-EmPOWER eNB agent  it says no such file or directory

**Comment by rriggio** [comment]
Not sure what you mean. You need to run just:

`git clone <repo>`

**Comment by mimo123-code** [comment]
Clone the 5G-EmPOWER eNB agent and protocols repository:

git@github.com:5g-empower/empower-enb-agent.git
THIS command does not work

**Comment by rriggio** [comment]
git clone https://github.com/5g-empower/empower-enb-agent.git

These are really the basics of GIT.
